name: Deploy ML Artifacts to Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create system temp folder
        run: mkdir -p /tmp/server

      - name: Clone ML repo and copy artifacts
        run: |
          git clone --branch deploy https://github.com/Dorkads/spellfixer-ml.git ml_repo
          cp -r ml_repo/ml_artifacts /tmp/server/

      - name: Copy backend files
        run: cp ml_model.py app.py /tmp/server/

      - name: Switch to deploy branch and replace contents
        run: |
          git checkout deploy || git checkout --orphan deploy
          rm -rf *
          mkdir server
          cp -r /tmp/server/* server/

      - name: Commit and push
        run: |
          git add .
          git commit -m "Deploy server/ with ML artifacts and backend code" || echo "No changes to commit"
          git push origin deploy --force
